-- ======================================================================
-- Your study database. Run this once in Supabase: SQL Editor -> New query
-- -> paste -> Run. Safe to run again.
--
-- DO NOT EDIT. These tables are what the app writes into. Build your own
-- views and tables in the `analysis` schema instead (created below).
-- ======================================================================

-- One visit to the app.
create table if not exists public.sessions (
  session_id   uuid primary key,
  user_id      uuid not null,          -- a BROWSER, not a person
  app          text not null,          -- which app wrote this row
  platform     text,                   -- 'mobile' | 'desktop' (null if unknown)
  browser      text,                   -- 'chrome' | 'safari' | 'firefox' | 'edge' | 'other'
  source       text,                   -- from ?src= or ?utm_source= in the link; null = none
  screen_w     integer,                -- window width in pixels
  is_test      boolean not null default false,   -- your own runs (?test=1)
  is_synthetic boolean not null default false,   -- practice data generated by the course
  started_at   timestamptz not null default now()
);

-- Every click on the app.
create table if not exists public.clicks (
  id          bigint generated always as identity primary key,
  session_id  uuid not null references public.sessions(session_id) on delete cascade,
  step        text not null,           -- the screen it happened on
  overlay     text,                    -- a layer open over that screen, if any
  x           double precision not null,   -- 0 = left edge of the app's frame, 1 = right
  y           double precision not null,   -- 0 = top of the frame, 1 = bottom
  seq         integer,                 -- 1st, 2nd, 3rd click on this screen in this visit
  hit         text not null,           -- what it landed on: 'option', 'back', 'none' = nothing
  created_at  timestamptz not null default now()
);

-- Every choice the app reports.
create table if not exists public.selections (
  id           bigint generated always as identity primary key,
  session_id   uuid not null references public.sessions(session_id) on delete cascade,
  step         text not null,          -- the screen the choice was made on
  value        text not null,          -- what was chosen
  duration_ms  integer not null,       -- time on that screen before choosing
  created_at   timestamptz not null default now()
);

-- A sign-in. `account` is a scrambled id: the same account always gives the
-- same value, but it cannot be turned back into an email.
create table if not exists public.identities (
  id          bigint generated always as identity primary key,
  session_id  uuid not null references public.sessions(session_id) on delete cascade,
  account     text not null,
  created_at  timestamptz not null default now()
);

create index if not exists clicks_session_idx on public.clicks (session_id);
create index if not exists selections_session_idx on public.selections (session_id);
create index if not exists identities_session_idx on public.identities (session_id);

-- ----------------------------------------------------------------------
-- Who may do what.
--   The app (anonymous): may only ADD rows. It can never read, change or
--   delete anything.
--   You (signed in to the dashboard): may only READ the raw tables.
-- Nobody can change or delete collected data from the app or dashboard.
-- ----------------------------------------------------------------------
alter table public.sessions   enable row level security;
alter table public.clicks     enable row level security;
alter table public.selections enable row level security;
alter table public.identities enable row level security;

do $$
declare t text;
begin
  foreach t in array array['sessions', 'clicks', 'selections', 'identities'] loop
    execute format('drop policy if exists "app adds rows" on public.%I', t);
    execute format('create policy "app adds rows" on public.%I for insert to anon with check (true)', t);
    execute format('drop policy if exists "you read rows" on public.%I', t);
    execute format('create policy "you read rows" on public.%I for select to authenticated using (true)', t);
  end loop;
end $$;

-- ----------------------------------------------------------------------
-- Your space. Views and tables you build for your analysis go here.
-- ----------------------------------------------------------------------
create schema if not exists analysis;
grant usage on schema analysis to authenticated;
alter default privileges in schema analysis grant select on tables to authenticated;

-- ----------------------------------------------------------------------
-- Check: four tables, each empty until the app records something.
-- ----------------------------------------------------------------------
select 'sessions' as table_name, count(*) from public.sessions
union all select 'clicks', count(*) from public.clicks
union all select 'selections', count(*) from public.selections
union all select 'identities', count(*) from public.identities;
