-- ======================================================================
-- Your study database. Run this once in Supabase: SQL Editor -> New query
-- -> paste -> Run. Safe to run again.
--
-- DO NOT EDIT. These tables are what the app writes into. Build your own
-- views in the `analysis` schema instead (created below).
-- ======================================================================

-- One visit to the app.
create table if not exists public.sessions (
  session_id   uuid primary key,
  user_id      uuid not null,          -- a BROWSER, not a person
  app          text not null,          -- which app wrote this row
  platform     text,                   -- 'mobile' | 'desktop' (null if unknown)
  browser      text,                   -- 'chrome' | 'safari' | 'firefox' | 'edge' | 'other'
  source       text,                   -- from ?src= or ?utm_source= in the link; null = none
  screen_w     integer,                -- window width in pixels
  is_test      boolean not null default false,   -- your own runs (?test=1)
  is_synthetic boolean not null default false,   -- practice data generated by the course
  started_at   timestamptz not null default now()
);

-- Every click on the app.
create table if not exists public.clicks (
  id          bigint generated always as identity primary key,
  session_id  uuid not null references public.sessions(session_id) on delete cascade,
  step        text not null,           -- the screen it happened on
  overlay     text,                    -- a layer open over that screen, if any
  x           double precision not null,   -- 0 = left edge of the app's frame, 1 = right
  y           double precision not null,   -- 0 = top of the frame, 1 = bottom
  seq         integer,                 -- 1st, 2nd, 3rd click on this screen in this visit
  hit         text not null,           -- what it landed on: 'option', 'back', 'none' = nothing
  created_at  timestamptz not null default now()
);

-- Every choice the app reports.
create table if not exists public.selections (
  id           bigint generated always as identity primary key,
  session_id   uuid not null references public.sessions(session_id) on delete cascade,
  step         text not null,          -- the screen the choice was made on
  value        text not null,          -- what was chosen
  duration_ms  integer not null,       -- time on that screen before choosing
  created_at   timestamptz not null default now()
);

-- A sign-in. `account` is a scrambled id: the same account always gives the
-- same value, but it cannot be turned back into an email.
create table if not exists public.identities (
  id          bigint generated always as identity primary key,
  session_id  uuid not null references public.sessions(session_id) on delete cascade,
  account     text not null,
  created_at  timestamptz not null default now()
);

create index if not exists clicks_session_idx on public.clicks (session_id);
create index if not exists selections_session_idx on public.selections (session_id);
create index if not exists identities_session_idx on public.identities (session_id);

-- ----------------------------------------------------------------------
-- Who may do what.
--   The app (anonymous): may only ADD rows. It can never read, change or
--   delete anything.
--   You (signed in to the dashboard): may only READ the raw tables.
-- Nobody can change or delete collected data from the app or dashboard.
-- ----------------------------------------------------------------------
alter table public.sessions   enable row level security;
alter table public.clicks     enable row level security;
alter table public.selections enable row level security;
alter table public.identities enable row level security;

do $$
declare t text;
begin
  foreach t in array array['sessions', 'clicks', 'selections', 'identities'] loop
    execute format('drop policy if exists "app adds rows" on public.%I', t);
    execute format('create policy "app adds rows" on public.%I for insert to anon with check (true)', t);
    execute format('drop policy if exists "you read rows" on public.%I', t);
    execute format('create policy "you read rows" on public.%I for select to authenticated using (true)', t);
  end loop;
end $$;

-- ----------------------------------------------------------------------
-- Your space. The views you build for your analysis go here.
-- ----------------------------------------------------------------------
create schema if not exists analysis;
-- Let websites (your dashboard) read `analysis`, next to `public`. This replaces the "Exposed
-- schemas" setting in Project Settings > Data API: from now on this line decides what is exposed.
alter role authenticator set pgrst.db_schemas = 'public, graphql_public, analysis';
notify pgrst, 'reload config';
grant usage on schema analysis to authenticated, service_role;
alter default privileges in schema analysis grant select on tables to authenticated, service_role;
grant select on all tables in schema analysis to service_role;   -- your assistant reads views to check them

-- ----------------------------------------------------------------------
-- Coursework: your checker answers and memo for each lesson, so your AI
-- assistant and every computer see the same progress. Not study data.
-- ----------------------------------------------------------------------
create table if not exists public.coursework (
  lesson        text not null,            -- 'lesson-01'
  question      text not null,            -- 'q1' … or 'memo'
  answer        text,                     -- the last answer checked, or the memo's text
  is_right      boolean not null default false,
  tries         integer not null default 0,
  submitted_at  timestamptz,              -- the memo: when it was submitted; a question: when it was given up
  updated_at    timestamptz not null default now(),
  primary key (lesson, question)
);
alter table public.coursework enable row level security;
drop policy if exists "coursework open" on public.coursework;
create policy "coursework open" on public.coursework for all to anon, authenticated using (true) with check (true);

-- What is in your space, for the dashboard's "Is your analysis tidy?" check:
-- every view and table in `analysis`, its definition (the comment you put on
-- it) and its SQL. Read-only; only a signed-in user may call it.
create or replace function public.analysis_catalog()
returns table (name text, kind text, definition text, sql text)
language sql stable security definer set search_path = ''
as $$
  select c.relname::text,
         case c.relkind when 'v' then 'view' when 'm' then 'materialized view' else 'table' end,
         pg_catalog.obj_description(c.oid, 'pg_class'),
         case when c.relkind in ('v', 'm') then pg_catalog.pg_get_viewdef(c.oid, true) end
  from pg_catalog.pg_class c
  join pg_catalog.pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'analysis' and c.relkind in ('v', 'm', 'r', 'p')
  order by 1;
$$;
revoke all on function public.analysis_catalog() from public, anon;
grant execute on function public.analysis_catalog() to authenticated;

-- For the setup check your AI assistant runs: did this exact test visit, and
-- a click in it, arrive? Answers yes or no for a visit id it was given, and
-- reveals nothing else.
create or replace function public.capture_arrived(sid uuid)
returns boolean
language sql stable security definer set search_path = ''
as $$
  select exists (select 1 from public.sessions where session_id = sid)
     and exists (select 1 from public.clicks where session_id = sid);
$$;
grant execute on function public.capture_arrived(uuid) to anon, authenticated;

-- For your AI assistant: builds your analysis (views in `analysis`) from the
-- files in analysis/, so you never paste SQL. Only your secret key may call it
-- (it lives in your Claude cloud environment, setup step 7); the publishable
-- key on your site cannot.
create or replace function public.analysis_apply(p_sql text)
returns text
language plpgsql security definer set search_path = ''
as $$
begin
  execute p_sql;
  notify pgrst, 'reload schema';     -- the dashboard sees new views at once
  return 'ok';
end;
$$;
revoke all on function public.analysis_apply(text) from public, anon, authenticated;
grant execute on function public.analysis_apply(text) to service_role;

-- ----------------------------------------------------------------------
-- Check: four tables, each empty until the app records something.
-- ----------------------------------------------------------------------
select 'sessions' as table_name, count(*) from public.sessions
union all select 'clicks', count(*) from public.clicks
union all select 'selections', count(*) from public.selections
union all select 'identities', count(*) from public.identities;
