/* =====================================================================
   study-core.js — capture, and nothing else.

   This is the part of the platform you do not build: it records what
   people do in the app, faithfully, into your database. Everything that
   turns those rows into numbers, charts and claims is yours.

   DO NOT EDIT THIS FILE. If capture breaks, every number after it is
   wrong and nothing will tell you. Use the health check on the dashboard
   to confirm capture works.

   What it records (see setup.sql for every column):
     sessions    — one visit: who (a browser id), when, which device, where
                   they came from (?src= or ?utm_source= in the link)
     clicks      — every click on the app, with its position inside the
                   app's frame (0–1 across, 0–1 down) and what it hit
     selections  — every choice the app reports: which screen, what value,
                   how long the person spent on that screen first
     identities  — when someone signs in, a scrambled id for the account,
                   so one person on two devices can be recognised

   What an app must tell it (Study.configure): its name, the element its
   screen is drawn in, which screen is showing, which overlay is open, and
   what a click landed on.
   ===================================================================== */

window.Study = (function () {
  'use strict';

  const params = new URLSearchParams(location.search);
  // Previews and demonstrations look at the app without being a visit.
  const PREVIEW_STEP = params.get('previewStep');
  const AUTHOR_MODE = params.get('authorMode') === '1';
  // Your own test runs: open the app with ?test=1. They are recorded with
  // is_test = true so you can tell them apart from real participants.
  const IS_TEST = params.get('test') === '1';

  let cfg = {
    app: null,
    screens: [],
    content: () => document.body,
    currentStep: () => null,
    currentOverlay: () => null,
    hitOf: () => 'none',
    onAppScreen: () => true,
    overlayActive: () => false
  };

  let PREVIEW_MODE = false;
  let TRACKING_OFF = true;
  let sessionId = null, sessionReady = Promise.resolve(), userId = null;
  let clickSeq = {};

  function newId() {
    try { return crypto.randomUUID(); }
    catch {
      return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, c => {
        const r = Math.random() * 16 | 0;
        return (c === 'x' ? r : (r & 0x3 | 0x8)).toString(16);
      });
    }
  }

  // A browser, not a person: the same person on a phone and a laptop gets
  // two of these, and a private window gets a fresh one every time.
  function browserId() {
    try {
      let id = localStorage.getItem('study_user_id');
      if (!id) { id = newId(); localStorage.setItem('study_user_id', id); }
      return id;
    } catch { return newId(); }
  }

  function platformOf() {
    const ua = navigator.userAgent || '';
    const touchMac = /Mac/i.test(navigator.platform || '') && navigator.maxTouchPoints > 1;
    return (/Android|iPhone|iPad|iPod|Mobile/i.test(ua) || touchMac) ? 'mobile' : 'desktop';
  }

  function browserOf() {
    const ua = navigator.userAgent || '';
    return /Edg\//.test(ua) ? 'edge' : /Firefox\//.test(ua) ? 'firefox'
         : /Chrome\//.test(ua) ? 'chrome' : /Safari\//.test(ua) ? 'safari' : 'other';
  }

  // Where the visit came from, as written in the link you shared:
  // ...?src=instagram  or  ...?utm_source=instagram. Empty when absent.
  const sourceOf = () => (params.get('src') || params.get('utm_source') || '').toLowerCase() || null;

  function begin() {
    sessionId = newId();
    clickSeq = {};
    if (TRACKING_OFF || !window.supabaseClient) { sessionReady = Promise.resolve(); return; }
    sessionReady = supabaseClient.from('sessions').insert({
      session_id: sessionId, user_id: userId, app: cfg.app,
      platform: platformOf(), browser: browserOf(), source: sourceOf(),
      screen_w: window.innerWidth, is_test: IS_TEST
    }).then(({ error }) => { if (error) console.error('session not recorded', error); });
  }

  // Every write waits for its session row, so nothing references a visit
  // that does not exist yet.
  async function write(table, row) {
    if (TRACKING_OFF || !window.supabaseClient) return;
    const sid = sessionId, ready = sessionReady;
    try {
      await ready;
      const { error } = await supabaseClient.from(table).insert({ session_id: sid, ...row });
      if (error) console.error(`${table} not recorded`, error);
    } catch (err) { console.error(`${table} not recorded`, err); }
  }

  function installClickLogger() {
    document.addEventListener('click', (e) => {
      if (cfg.overlayActive() || !cfg.onAppScreen()) return;
      const box = cfg.content();
      if (!box) return;
      const r = box.getBoundingClientRect();
      if (!r.width || !r.height) return;
      const step = cfg.currentStep();
      if (!step) return;
      const t = e.target instanceof Element ? e.target : null;
      clickSeq[step] = (clickSeq[step] || 0) + 1;
      write('clicks', {
        step,
        overlay: cfg.currentOverlay(),
        // Relative to the app's frame, so the same button has the same
        // position on every device. Outside 0–1 = a click beside the frame.
        x: (e.clientX - r.left) / r.width,
        y: (e.clientY - r.top) / r.height,
        seq: clickSeq[step],
        hit: t ? (cfg.hitOf(t) || 'none') : 'none'
      });
    }, true);
  }

  // The app reports a choice: on which screen, what the person pressed (label, as it reads on screen),
  // what it recorded (value: usually the screen it led to), and how long they had been on that screen.
  // Returns false at once (the app reads it as "nothing else changed the screen"); the write runs on its own.
  function choice(step, value, durationMs, label) {
    const row = { step, value: String(value), duration_ms: Math.max(0, durationMs | 0) };
    if (!label) { write('selections', row); return false; }
    row.label = String(label).slice(0, 80);
    writeChoice(row);
    return false;
  }
  // A database set up before `label` existed has no such column: keep the choice, drop the label.
  async function writeChoice(row) {
    if (TRACKING_OFF || !window.supabaseClient) return;
    const sid = sessionId;
    try {
      await sessionReady;
      const { error } = await supabaseClient.from('selections').insert({ session_id: sid, ...row });
      if (error && /label/.test(error.message || '')) { const { label, ...rest } = row; write('selections', rest); }
      else if (error) console.error('selections not recorded', error);
    } catch (err) { console.error('selections not recorded', err); }
  }

  // Someone signed in. The account is scrambled before it leaves the
  // browser: you can tell two visits are the same account, never whose.
  async function identify(email) {
    if (!email) return;
    try {
      const bytes = new TextEncoder().encode(String(email).trim().toLowerCase());
      const digest = await crypto.subtle.digest('SHA-256', bytes);
      const account = [...new Uint8Array(digest)].slice(0, 8)
        .map(b => b.toString(16).padStart(2, '0')).join('');
      write('identities', { account });
    } catch (err) { console.error('identity not recorded', err); }
  }

  async function startStudy() {
    begin();
    return { started: false, offer: false };
  }

  function configure(options) {
    cfg = { ...cfg, ...options };
    PREVIEW_MODE = !!PREVIEW_STEP && cfg.screens.includes(PREVIEW_STEP);
    TRACKING_OFF = PREVIEW_MODE || AUTHOR_MODE;
    userId = browserId();
    sessionId = newId();
    if (!TRACKING_OFF) installClickLogger();
    if (!TRACKING_OFF && !window.supabaseClient) {
      console.error(`Study: '${cfg.app}' should record, but there is no database client. Nothing will be saved.`);
    }
    return api;
  }

  const escapeHtml = s => String(s).replace(/[&<>"']/g,
    c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));

  const api = {
    configure, begin, write, choice, identify, startStudy, escapeHtml, newId,
    // Tasks are not part of this platform yet: these keep apps written for
    // a fuller platform working, and do nothing.
    beginTasks() {}, giveUp() {}, currentTask: () => null, inBattery: () => false,
    previewState: () => null, routeRetry: false,
    contentRect() {
      const b = cfg.content && cfg.content();
      const r = b && b.getBoundingClientRect();
      return r && r.width && r.height ? r : null;
    },
    get sessionId() { return sessionId; },
    get userId() { return userId; },
    get PREVIEW_MODE() { return PREVIEW_MODE; },
    get PREVIEW_STEP() { return PREVIEW_STEP; },
    get TRACKING_OFF() { return TRACKING_OFF; },
    AUTHOR_MODE,
    QUESTION_PREVIEW: false,
    IS_TEST
  };
  return api;
})();
